
(*Note: this grammar is not 100% accurate (nor can it be in a single unified parser/lexer context-free grammar) but should serve as an alright basic reference for writing a lexer and parser in combination with a broader understanding of the language itself*)

<program>       ::= <newline-character>* (<statement> <newline-character>*)* ;

<statement>     ::= <comment> | (<include> | <definition> | <term>) (<newline-character> | <EOF>) ;

<comment>       ::= ";" <UTF8-character>* ";"
                  | ";" <comment> ";" ;

<include>       ::= ("io-include" | "io-include-permissive") """ <UTF8-character>* """ ;

<definition>    ::= ("define" | "define-unsafe") <pure symbol> <term> ;

<term>          ::= <abstraction> | <application> ;

<abstraction>   ::= "\" <pure symbol> "." <term> ;

<application>   ::= <atom>+ ;

<atom>          ::= <pure symbol> | "(" <term> ")" | <abstraction> | <impure symbol> ;

<pure symbol>   ::= <letter> (<letter> | <digit> | "-" )* ;

<impure symbol> ::= ["`"] <digit>+
                  | ["`"] ("#t" | "#f")
                  | ["`"] "<" <term> "," <term> ">"
                  | ["`"] "[" [<term> ("," <term>)*] "]"
                  | ["`"] "{" [<term> ("," <term>)*] "}"
                  | ["`"] "'" <ASCII-character> "'"
                  | ["`"] """ <UTF8-character>* """ 
                  | "io-church-to-int"
                  | "io-int-to-church"
                  | "io-church-to-pair"
                  | "io-pair-to-church"
                  | "io-church-to-bool"
                  | "io-bool-to-church"
                  | "io-church-to-list"
                  | "io-list-to-church"
                  | "io-scott-to-list"
                  | "io-list-to-scott"
                  | "io-church-to-char"
                  | "io-char-to-church"
                  | "io-scott-to-string"
                  | "io-string-to-scott" 
                  | "io-input" """ <UTF8-character>* """;

